<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <WasmMainJSPath>wwwroot\main.js</WasmMainJSPath>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" Version="11.3.0" />
    <ProjectReference Include="..\SveloniaApp\SveloniaApp.csproj" />
  </ItemGroup>
</Project>
