<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.*" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.*" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Svelonia.Physics\Svelonia.Physics.csproj" />
  </ItemGroup>

</Project>
