using Avalonia;
using Avalonia.Controls;

using Svelonia.Core;
namespace Svelonia.Fluent;

/// <summary>
/// 
/// </summary>
public static class ResponsiveExtensions
{
    /// <summary>
    /// Generic binding for any Avalonia Property using State/Computed.
    /// </summary>
    public static T Bind<T, V>(this T control, AvaloniaProperty<V> property, State<V> state)
        where T : Control
    {
        Binder.Bind(control, property, state);
        return control;
    }

    // --- Layout Properties (Removed: Generated by BindingGenerator) ---

    // FontSize: Generated by BindingGenerator for specific types (TextBlock, TemplatedControl).
    // We removed the generic Control extension to avoid ambiguity.

    // --- Grid Properties ---
    // Note: ColumnDefinitions/RowDefinitions are strings or specific types, parsing might be needed.
    // For simplicity, assuming the user provides ColumnDefinitions object or string if implicit conversion works.
    // Actually ColumnDefinitions is a collection, direct binding might be tricky. 
    // Usually simpler to just swap content or use Star/Auto widths numerically if wrapper exists.
}
